[tools]
bun = "1.3.9"
node = "24.12.0"
go = "1.26.3"
rust = "1.89.0"
starship = "1.25.1"
atuin = "18.16.1"
uv = "0.9.27"
"github:ogulcancelik/herdr" = "0.5.8"

[settings]
experimental = true
yes = true
